/**
 * v1 GCodeGenerator (frontend/src/services/slicer/GCodeGenerator.ts) 이식.
 *
 * 동작을 v1 과 동일하게 유지하기 위해 수치·순서·포맷 문자열·메서드 구조를
 * 변경하지 않았다 (v1 원본과 diff 대조 가능).
 *
 * v1 과의 차이점(의도된 것):
 *   - LayerData(DLP 필드 포함) 대신 이 레이어의 polygons: Point[][] 만 받는다.
 *     generateLayer 가 실제로 layerData 에서 쓰는 것은 polygons 뿐이었다.
 *   - PolygonClipper 는 ./polygon-clipper.ts 로 v1 원본 그대로 이식.
 *   - [Step 1-1b] 레이어 preamble 에서 G92 E0 방출 (v1 미방출 결함 수정).
 *     v1 은 M82(절대 E) 헤더를 방출하면서도 레이어마다 currentE 를 0 에서 재시작하고
 *     레이어 경계에 G92 E0 를 넣지 않아, 절대 E 모드 프린터가 각 레이어 첫 압출을
 *     이전 레이어 누적량만큼의 대량 리트랙트로 오해석했다. 이제 각 레이어 시작에
 *     G92 E0 를 방출해 프린터 절대 E 좌표를 레이어 로컬 currentE(=0)와 정합시킨다.
 *     → 이 파일은 v1 대비 산출 G-code 가 의도적으로 달라지는 첫 지점이다
 *       (레이어마다 "G92 E0 ; 압출 좌표 리셋" 라인 1 줄 추가).
 *
 * 구조(리팩토링): 순수 기하 함수는 gcode-geometry.ts, 스캔라인 인필은
 * infill-generator.ts 로 분리했고, generateLayer 는 단계별 private 메서드로
 * 쪼갰다 (buildWallPaths/buildGapFill/buildInfillBoundaries/buildInfillLines/
 * emitPaths/emitInfillLines). 산출 G-code 문자열은 바이트 단위로 동일하다.
 */
import { Point, PathSegment, GCodePath, FdmSettings } from './types';
import { PolygonClipper } from './polygon-clipper';
import { optimizePaths, calculatePathLength } from './gcode-geometry';
import { generateGlobalInfill } from './infill-generator';

/**
 * generateLayer 내부에서 세그먼트를 누적하며 흐르는 가변 상태.
 * 원본의 클로저 지역변수(gcode/currentE/currentX/currentY/isRetracted/pathSegments)를
 * 메서드 간에 참조로 넘기기 위한 컨텍스트. z 는 레이어 높이(z-hop 계산용).
 */
interface EmitContext {
    z: number;
    gcode: string;
    currentE: number;
    currentX: number;
    currentY: number;
    isRetracted: boolean;
    pathSegments: PathSegment[];
}

export class GCodeGenerator {
    private settings: FdmSettings;

    constructor(settings: FdmSettings) {
        this.settings = settings;
    }

    public generateHeader(): string {
        const s = this.settings;
        let h = '';
        h += '; Generated by MazicAlign Slicer\n';
        h += `; Layer Height: ${s.layerHeight}mm, Nozzle: ${s.nozzleDiameter}mm\n`;
        h += `; Temperature: Nozzle ${s.nozzleTemp}C, Bed ${s.bedTemp}C\n`;
        h += '\n';
        h += 'G90 ; absolute positioning\n';
        h += 'M82 ; extruder absolute mode\n';
        h += 'G28 ; home all axes\n';
        h += `M140 S${s.bedTemp} ; set bed temp\n`;
        h += `M104 S${s.nozzleTemp} ; set nozzle temp\n`;
        h += `M190 S${s.bedTemp} ; wait for bed temp\n`;
        h += `M109 S${s.nozzleTemp} ; wait for nozzle temp\n`;
        h += 'G92 E0 ; reset extruder\n';
        h += 'M107 ; fan off\n';
        h += '\n';
        return h;
    }

    public generateFooter(): string {
        let f = '\n; === END ===\n';
        // 절대 E 모드(M82) 정합: 리셋 없이는 아래 E-5 가 "마지막 레이어 누적량 - 5" 로
        // 해석되어 종료 리트랙트가 5mm 가 아니게 된다. 레이어 preamble 과 같은 취지의 리셋.
        f += 'G92 E0 ; 압출 좌표 리셋 (종료 리트랙트 기준점)\n';
        f += 'G1 E-5 F1800 ; retract\n';
        f += 'G91 ; relative\n';
        f += 'G0 Z10 ; raise Z\n';
        f += 'G90 ; absolute\n';
        f += 'G0 X0 Y0 F3000 ; home XY\n';
        f += 'M104 S0 ; nozzle off\n';
        f += 'M140 S0 ; bed off\n';
        f += 'M107 ; fan off\n';
        f += 'M84 ; steppers off\n';
        return f;
    }

    public generateLayerPreamble(layerIndex: number): string {
        let pre = '';
        // 절대 E 모드(M82) 정합: generateLayer 는 레이어마다 currentE 를 0 에서 다시 시작하므로,
        // 각 레이어 시작에서 프린터의 절대 E 좌표도 0 으로 리셋해야 한다.
        // 미방출 시 다음 레이어의 첫 G1 E 값이 이전 누적량 대비 대량 리트랙트로 오해석된다.
        // (레이어는 항상 언리트랙트 상태로 끝나므로 — 마지막 경로 명령이 extrude —
        //  이 리셋이 보류 중인 리트랙트 오프셋을 지우는 경우는 없다.)
        pre += 'G92 E0 ; 압출 좌표 리셋\n';
        if (layerIndex === this.settings.fanDisableLayerCount) {
            const pwm = Math.round((this.settings.fanSpeed / 100) * 255);
            pre += `M106 S${pwm} ; fan on ${this.settings.fanSpeed}%\n`;
        }
        return pre;
    }

    public generateLayer(polygons: Point[][], z: number, layerIndex: number): { gcode: string, paths: GCodePath } {
        const ctx: EmitContext = {
            z,
            gcode: `; Layer ${layerIndex}, Z=${z.toFixed(3)}\n`,
            currentE: 0,
            currentX: 0,
            currentY: 0,
            isRetracted: false,
            pathSegments: [],
        };
        ctx.gcode += `G0 Z${z.toFixed(3)}\n`;
        ctx.gcode += this.generateLayerPreamble(layerIndex);

        // 1. Clean Input (Union all polygons to handle overlaps/self-intersections)
        // Note: Clipper Union expects non-self-intersecting inputs usually, but it handles them well.
        // We treat all polygons as "Positive" initially?
        // Actually, layerData.polygons comes from Three.js triangulation which might be messy.
        // But usually it's a set of contours.
        // Clipper's Union with NonZero rule should handle it if we orient them correctly?
        // Or we just pass them all to Union.

        // Better: Just use the raw polygons as the "Model Boundary".
        const modelBoundary = PolygonClipper.union(polygons);

        // 2. Generate Walls (Concentric Shells)
        const walls = this.buildWallPaths(modelBoundary);

        // 3. Gap Filling (Robust)
        this.buildGapFill(modelBoundary, walls.currentOffset, walls.wallSpacing, walls.innerWalls);

        // 4. Infill Boundary (for < 100% infill)
        const infillBoundaries = this.buildInfillBoundaries(
            modelBoundary, walls.isSolid, walls.currentOffset, walls.wallSpacing,
        );

        // 5. Optimize Path Order
        // Optimize Outer and Inner separately
        const optimizedOuter = optimizePaths(walls.outerWalls, { x: ctx.currentX, y: ctx.currentY });
        const optimizedInner = optimizePaths(walls.innerWalls, { x: ctx.currentX, y: ctx.currentY }); // Inner walls + Gap fills

        // 6. Generate Global Infill (Rectilinear/Grid for < 100%)
        const infillLines = this.buildInfillLines(walls.isSolid, infillBoundaries);

        // 7. Execute Print Sequence
        if (this.settings.printOrder === 'infill-first') {
            // Infill First: Inner Walls (Concentric) -> Infill Lines (Rectilinear) -> Outer Walls
            this.emitPaths(ctx, optimizedInner); // Concentric Infill + Gap Fills
            this.emitInfillLines(ctx, infillLines);         // Rectilinear Infill (if any)
            this.emitPaths(ctx, optimizedOuter); // Outer Walls
        } else {
            // Walls First: Outer Walls -> Inner Walls -> Infill Lines
            this.emitPaths(ctx, optimizedOuter);
            this.emitPaths(ctx, optimizedInner);
            this.emitInfillLines(ctx, infillLines);
        }

        return { gcode: ctx.gcode, paths: { segments: ctx.pathSegments, totalExtrusion: ctx.currentE } };
    }

    /**
     * 세그먼트 1개 방출 (자동 리트랙션 포함). 원본 generateLayer 의 addSegment 클로저.
     * ctx 의 gcode/currentE/currentX/currentY/isRetracted/pathSegments 를 갱신한다.
     */
    private addSegment(
        ctx: EmitContext,
        x: number,
        y: number,
        type: 'move' | 'extrude',
        extrusionAmount: number = 0,
    ): void {
        const z = ctx.z;
        if (type === 'move') {
            const dist = Math.hypot(x - ctx.currentX, y - ctx.currentY);
            if (dist < 0.001) return; // Already there

            // Retract before long travel
            if (this.settings.enableRetraction && dist >= this.settings.retractMinTravelDistance && !ctx.isRetracted) {
                ctx.currentE -= this.settings.retractLength;
                ctx.gcode += `G1 E${ctx.currentE.toFixed(4)} F${this.settings.retractSpeed * 60} ; retract\n`;
                ctx.pathSegments.push({ x: ctx.currentX, y: ctx.currentY, type: 'retract', extrusion: this.settings.retractLength });
                if (this.settings.retractZHop > 0) {
                    ctx.gcode += `G0 Z${(z + this.settings.retractZHop).toFixed(3)} ; z-hop\n`;
                }
                ctx.isRetracted = true;
            }

            ctx.gcode += `G0 X${x.toFixed(3)} Y${y.toFixed(3)} F${this.settings.fdmSpeed * 60}\n`;
            ctx.pathSegments.push({ x, y, type: 'move' });
            ctx.currentX = x;
            ctx.currentY = y;

        } else if (type === 'extrude') {
            // Un-retract before extrusion
            if (ctx.isRetracted) {
                if (this.settings.retractZHop > 0) {
                    ctx.gcode += `G0 Z${z.toFixed(3)} ; z-hop recover\n`;
                }
                ctx.currentE += this.settings.retractLength;
                ctx.gcode += `G1 E${ctx.currentE.toFixed(4)} F${this.settings.retractSpeed * 60} ; un-retract\n`;
                ctx.isRetracted = false;
            }

            ctx.gcode += `G1 X${x.toFixed(3)} Y${y.toFixed(3)} E${(ctx.currentE + extrusionAmount).toFixed(4)} F${this.settings.fdmSpeed * 60}\n`;
            ctx.currentE += extrusionAmount;
            ctx.pathSegments.push({ x, y, type: 'extrude', extrusion: extrusionAmount });
            ctx.currentX = x;
            ctx.currentY = y;
        }
    }

    /**
     * 2. 동심 벽(Concentric Shells) 생성. 모델 경계를 안쪽으로 오프셋하며
     * 외곽 벽(perimeter)과 내부 벽(concentric infill)을 나눈다.
     * gap fill / infill boundary 계산에 필요한 currentOffset·wallSpacing·isSolid 도 함께 반환.
     */
    private buildWallPaths(modelBoundary: Point[][]): {
        outerWalls: Point[][];
        innerWalls: Point[][];
        currentOffset: number;
        wallSpacing: number;
        isSolid: boolean;
    } {
        const outerWalls: Point[][] = [];
        const innerWalls: Point[][] = []; // For 100% infill (Concentric Infill)

        const nozzle = this.settings.nozzleDiameter;

        // Systematic Fix for 100% Density:
        const isSolid = this.settings.infillPercentage === 100;
        const totalCount = isSolid ? 9999 : this.settings.wallCount;
        const wallCountSetting = this.settings.wallCount;

        const outerOverlap = (this.settings.outerWallOverlapPercentage || 0) / 100;
        // Clamp wall overlap to max 0.95 to prevent infinite loop
        const wallOverlap = Math.min((this.settings.wallOverlapPercentage || 0) / 100, 0.95);
        const wallSpacing = Math.max(nozzle * (1 - wallOverlap), 0.01);

        // We generate walls by offsetting the Model Boundary inwards.
        let currentOffset = -(nozzle * 0.5) * (1 - outerOverlap);

        // For Infill Boundary calculation
        // let lastWallBoundary: Point[][] = modelBoundary; // Unused

        for (let i = 0; i < totalCount; i++) {
            const wallCenters = PolygonClipper.offset(modelBoundary, currentOffset);

            if (wallCenters.length === 0) break; // No more space

            // Optimization: Filter tiny loops
            // For 100% infill, we might want to keep even small loops to fill voids?
            // But nozzle diameter limit still applies.
            const validWalls = wallCenters.filter(p => calculatePathLength(p) > nozzle * 1.5);

            if (validWalls.length > 0) {
                // Separate Outer Walls (Perimeters) from Inner Walls (Concentric Infill)
                if (i < wallCountSetting) {
                    outerWalls.push(...validWalls);
                } else {
                    innerWalls.push(...validWalls);
                }
                // Update last boundary for infill (approximate)
                // Actually, the "Inner Boundary" of this wall is: Center - nozzle/2
                // But for the NEXT wall, we use the global offset from modelBoundary.
            } else {
                // If we have walls but they are too small, and we are in 100% mode,
                // we should stop. Tiny artifacts don't need 9000 iterations.
                break;
            }

            currentOffset -= wallSpacing;

            // Safety break: If offset is absurdly large (e.g. > 500mm), stop.
            // Assuming model is centered or reasonable size.
            if (currentOffset < -500) break;
        }

        return { outerWalls, innerWalls, currentOffset, wallSpacing, isSolid };
    }

    /**
     * 3. 갭 필링 (Robust). 마지막 벽 안쪽 좁은 void 를 찾아 innerWalls 에 채운다.
     * innerWalls 를 in-place 로 확장한다 (원본과 동일).
     */
    private buildGapFill(
        modelBoundary: Point[][],
        currentOffset: number,
        wallSpacing: number,
        innerWalls: Point[][],
    ): void {
        // Add gap fills to innerWalls (treat as infill)
        if (this.settings.enableGapFilling) {
            const nozzle = this.settings.nozzleDiameter;
            // Calculate the boundary of the remaining void
            // The last wall's inner edge was at: lastValidOffset - (nozzle/2)
            const lastValidOffset = currentOffset + wallSpacing;
            // The void is inside the last generated wall.
            // Last wall center was at `lastValidOffset`.
            // Inner edge of last wall is `lastValidOffset - nozzle/2`.

            // We want to find voids inside the last wall.
            // But if we used Concentric Infill, we might have filled everything.
            // So we check the offset from the LAST generated wall.

            // Actually, simpler: Just check voids inside the last generated wall boundary.
            // If we generated ANY walls, the last one is the boundary.
            // If not, modelBoundary is the boundary.

            // Let's use the `currentOffset` which is where the NEXT wall would have been.
            // If we stopped, it means `offset(currentOffset)` was empty.
            // But maybe `offset(currentOffset + small)` is not empty?

            // Let's stick to the previous logic: check voids inside the last wall.
            // But we need the polygon of the last wall.
            // Since we don't have it easily (it's in outerWalls or innerWalls),
            // let's re-calculate the void boundary based on the last offset.

            // The "Void" is whatever is inside the last wall we successfully printed.
            // Last successful offset was `lastValidOffset`.
            // The inner edge of that wall is `lastValidOffset - nozzle/2`.

            const voidBoundaryOffset = lastValidOffset - (nozzle * 0.5);
            const voidPolys = PolygonClipper.offset(modelBoundary, voidBoundaryOffset);

            if (voidPolys.length > 0) {
                // Check if these voids are "narrow" (i.e., too small for standard infill)
                // Heuristic: If we offset inwards by nozzle width and it disappears or shrinks significantly, it's narrow.
                // Or simply: If it's small, fill it.

                const innerCheck = PolygonClipper.offset(voidPolys, -nozzle);

                // Aggressive Gap Filling Strategy:
                // If the void is too small for standard infill (innerCheck empty), we MUST fill it.
                // We generate a path that traces the perimeter of the void, slightly inset.
                // Even if the void is tiny (e.g. 0.1mm), a 0.4mm nozzle tracing it will fill it (and overlap walls).
                // This is acceptable/desired to prevent internal voids.

                if (innerCheck.length === 0) {
                    // Generate a wall slightly inside the void boundary (epsilon offset)
                    // -0.05mm ensures we are mathematically inside the void, but the nozzle (0.4mm) will cover the void + overlap.
                    const gapWalls = PolygonClipper.offset(voidPolys, -0.05);
                    if (gapWalls.length > 0) {
                        innerWalls.push(...gapWalls);
                    } else {
                        // If even -0.05 fails, the void is microscopic (< 0.1mm width).
                        // In this case, we might skip it, or try an even smaller offset?
                        // Clipper handles scaling, so it should work unless it's truly degenerate.
                        // Let's try to print the void boundary itself if offset fails.
                        innerWalls.push(...voidPolys);
                    }
                }
            }
        }
    }

    /**
     * 4. 인필 경계 계산 (< 100% infill 일 때). 마지막 벽 안쪽에서 오버랩만큼
     * 바깥으로 되민 경계를 반환한다. solid(100%)면 빈 배열.
     */
    private buildInfillBoundaries(
        modelBoundary: Point[][],
        isSolid: boolean,
        currentOffset: number,
        wallSpacing: number,
    ): Point[][] {
        let infillBoundaries: Point[][] = [];
        if (!isSolid) {
            const nozzle = this.settings.nozzleDiameter;
            const lastValidOffset = currentOffset + wallSpacing;
            const infillOverlap = nozzle * ((this.settings.infillOverlapPercentage || 15) / 100);
            const infillOffset = lastValidOffset - (nozzle * 0.5) + infillOverlap;
            infillBoundaries = PolygonClipper.offset(modelBoundary, infillOffset);
        }
        return infillBoundaries;
    }

    /**
     * 6. 전역 인필 라인 생성 (Rectilinear/Grid, < 100%). grid 는 0°+90° 두 방향.
     */
    private buildInfillLines(isSolid: boolean, infillBoundaries: Point[][]): [Point, Point][] {
        const infillLines: [Point, Point][] = [];
        if (!isSolid && this.settings.infillPercentage > 0 && infillBoundaries.length > 0) {
            const nozzle = this.settings.nozzleDiameter;
            const pattern = this.settings.infillPattern || 'lines';
            // const nozzle = this.settings.nozzleDiameter; // Already defined

            if (pattern === 'grid') {
                infillLines.push(...generateGlobalInfill(infillBoundaries, this.settings.infillPercentage, nozzle, 0));
                infillLines.push(...generateGlobalInfill(infillBoundaries, this.settings.infillPercentage, nozzle, 90));
            } else {
                infillLines.push(...generateGlobalInfill(infillBoundaries, this.settings.infillPercentage, nozzle, 0));
            }
        }
        return infillLines;
    }

    /**
     * 7-a. 벽/경로 집합을 인쇄한다 (각 폐루프: move → extrude*, 마지막에 loop close).
     * 원본 generateLayer 의 printPaths 클로저.
     */
    private emitPaths(ctx: EmitContext, paths: Point[][]): void {
        for (const wall of paths) {
            if (wall.length === 0) continue;
            this.addSegment(ctx, wall[0].x, wall[0].y, 'move');
            for (let i = 1; i < wall.length; i++) {
                const p = wall[i];
                const prev = wall[i - 1];
                const dist = Math.hypot(p.x - prev.x, p.y - prev.y);
                const e = this.calculateExtrusion(dist);
                this.addSegment(ctx, p.x, p.y, 'extrude', e);
            }
            // Close loop
            const start = wall[0];
            const end = wall[wall.length - 1];
            const dist = Math.hypot(start.x - end.x, start.y - end.y);
            const e = this.calculateExtrusion(dist);
            this.addSegment(ctx, start.x, start.y, 'extrude', e);
        }
    }

    /**
     * 7-b. 인필 라인을 인쇄한다. zigzag/grid 는 인접 라인 끝점이 가까우면 연속 압출로 잇는다.
     * 원본 generateLayer 의 printInfillLines 클로저.
     */
    private emitInfillLines(ctx: EmitContext, infillLines: [Point, Point][]): void {
        if (infillLines.length === 0) return;

        const spacing = this.settings.nozzleDiameter * (100 / this.settings.infillPercentage);
        const connectionThreshold = spacing * 1.5;
        const pattern = this.settings.infillPattern || 'lines';

        for (let i = 0; i < infillLines.length; i++) {
            const line = infillLines[i];

            let isConnected = false;
            if (i > 0 && (pattern === 'zigzag' || pattern === 'grid')) {
                const prevLine = infillLines[i - 1];
                const prevEnd = prevLine[1];
                const currStart = line[0];
                const dist = Math.hypot(currStart.x - prevEnd.x, currStart.y - prevEnd.y);

                if (dist < connectionThreshold) {
                    isConnected = true;
                }
            }

            if (isConnected) {
                const start = line[0];
                const dist = Math.hypot(start.x - ctx.currentX, start.y - ctx.currentY);
                const e = this.calculateExtrusion(dist);
                this.addSegment(ctx, start.x, start.y, 'extrude', e);
            } else {
                this.addSegment(ctx, line[0].x, line[0].y, 'move');
            }

            const dist = Math.hypot(line[1].x - line[0].x, line[1].y - line[0].y);
            const e = this.calculateExtrusion(dist);
            this.addSegment(ctx, line[1].x, line[1].y, 'extrude', e);
        }
    }

    private calculateExtrusion(distance: number): number {
        const filamentDiameter = 1.75;
        const filamentArea = Math.PI * Math.pow(filamentDiameter / 2, 2);
        const volume = distance * this.settings.nozzleDiameter * this.settings.layerHeight;
        return (volume / filamentArea) * this.settings.fdmExtrusionRate;
    }
}
